/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group3_finalproject_omp;
import database.LoginDatabase;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author yuuki
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        
        jLOGINGUEST.setVisible(false);
        jLOGINLIBRARIAN.setVisible(false);
        jLOGINADMIN.setVisible(false);
        
        setIconImage(new ImageIcon(getClass().getResource("/image_main/ONEMOREPAGE (Logo).png")).getImage());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLOGINGUEST = new javax.swing.JPanel();
        jG_EXIT = new javax.swing.JLabel();
        jG_USERNAME = new javax.swing.JTextField();
        jG_PASSWORD = new javax.swing.JPasswordField();
        jG_LOGIN = new javax.swing.JButton();
        jBG_GUEST = new javax.swing.JLabel();
        jLOGINLIBRARIAN = new javax.swing.JPanel();
        jL_EXIT = new javax.swing.JLabel();
        jL_LIBRARIAN_ID = new javax.swing.JTextField();
        jL_PASSWORD = new javax.swing.JPasswordField();
        jL_LOGIN = new javax.swing.JButton();
        jBG_LIBRARIAN = new javax.swing.JLabel();
        jLOGINADMIN = new javax.swing.JPanel();
        jA_EXIT = new javax.swing.JLabel();
        jA_ADMIN_ID = new javax.swing.JTextField();
        jA_PASSWORD = new javax.swing.JPasswordField();
        jA_KEYCARD = new javax.swing.JTextField();
        jA_LOGIN = new javax.swing.JButton();
        jBG_ADMIN = new javax.swing.JLabel();
        OMP_Logo = new javax.swing.JLabel();
        jAboutUs = new javax.swing.JLabel();
        jbCreateAcc = new javax.swing.JButton();
        GUEST_PORTAL = new javax.swing.JLabel();
        LIBRARIAN_PORTAL = new javax.swing.JLabel();
        ADMIN_PORTAL = new javax.swing.JLabel();
        jBestChoice = new javax.swing.JLabel();
        ONEMOREPAGE = new javax.swing.JLabel();
        jShortDesc = new javax.swing.JLabel();
        jDivider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main | One More Page");
        setLocation(new java.awt.Point(380, 180));
        setPreferredSize(new java.awt.Dimension(1190, 695));
        setResizable(false);
        setSize(new java.awt.Dimension(1190, 695));

        jPanel1.setBackground(new java.awt.Color(255, 254, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLOGINGUEST.setBackground(new java.awt.Color(131, 157, 111));
        jLOGINGUEST.setMaximumSize(new java.awt.Dimension(500, 500));
        jLOGINGUEST.setPreferredSize(new java.awt.Dimension(500, 500));
        jLOGINGUEST.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jG_EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/EXIT_GREEN.png"))); // NOI18N
        jG_EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jG_EXITMouseClicked(evt);
            }
        });
        jLOGINGUEST.add(jG_EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 22, -1, -1));

        jG_USERNAME.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jG_USERNAME.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jG_USERNAME.setToolTipText("");
        jG_USERNAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 114, 54), 2));
        jLOGINGUEST.add(jG_USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 201, 400, 45));

        jG_PASSWORD.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jG_PASSWORD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 114, 54), 2));
        jLOGINGUEST.add(jG_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 296, 400, 45));

        jG_LOGIN.setBackground(new java.awt.Color(187, 234, 151));
        jG_LOGIN.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jG_LOGIN.setForeground(new java.awt.Color(79, 114, 54));
        jG_LOGIN.setText("LOG IN");
        jG_LOGIN.setBorder(null);
        jG_LOGIN.setDefaultCapable(false);
        jG_LOGIN.setFocusPainted(false);
        jG_LOGIN.setFocusable(false);
        jG_LOGIN.setRequestFocusEnabled(false);
        jG_LOGIN.setRolloverEnabled(false);
        jG_LOGIN.setVerifyInputWhenFocusTarget(false);
        jG_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jG_LOGINActionPerformed(evt);
            }
        });
        jLOGINGUEST.add(jG_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 100, 40));

        jBG_GUEST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/LOGIN_STUENT.png"))); // NOI18N
        jLOGINGUEST.add(jBG_GUEST, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jPanel1.add(jLOGINGUEST, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 88, 500, 500));

        jLOGINLIBRARIAN.setBackground(new java.awt.Color(131, 157, 111));
        jLOGINLIBRARIAN.setMaximumSize(new java.awt.Dimension(500, 500));
        jLOGINLIBRARIAN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/EXIT_BLUE.png"))); // NOI18N
        jL_EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_EXITMouseClicked(evt);
            }
        });
        jLOGINLIBRARIAN.add(jL_EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 22, -1, -1));

        jL_LIBRARIAN_ID.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jL_LIBRARIAN_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jL_LIBRARIAN_ID.setToolTipText("");
        jL_LIBRARIAN_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 104, 126), 2));
        jLOGINLIBRARIAN.add(jL_LIBRARIAN_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 201, 400, 45));

        jL_PASSWORD.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jL_PASSWORD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 104, 126), 2));
        jLOGINLIBRARIAN.add(jL_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 296, 400, 45));

        jL_LOGIN.setBackground(new java.awt.Color(202, 231, 255));
        jL_LOGIN.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jL_LOGIN.setForeground(new java.awt.Color(88, 104, 126));
        jL_LOGIN.setText("LOG IN");
        jL_LOGIN.setBorder(null);
        jL_LOGIN.setDefaultCapable(false);
        jL_LOGIN.setFocusPainted(false);
        jL_LOGIN.setFocusable(false);
        jL_LOGIN.setRequestFocusEnabled(false);
        jL_LOGIN.setRolloverEnabled(false);
        jL_LOGIN.setVerifyInputWhenFocusTarget(false);
        jL_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jL_LOGINActionPerformed(evt);
            }
        });
        jLOGINLIBRARIAN.add(jL_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 100, 40));

        jBG_LIBRARIAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/LOGIN_LIBRARIAN.png"))); // NOI18N
        jLOGINLIBRARIAN.add(jBG_LIBRARIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jPanel1.add(jLOGINLIBRARIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 88, 500, 500));

        jLOGINADMIN.setBackground(new java.awt.Color(131, 157, 111));
        jLOGINADMIN.setMaximumSize(new java.awt.Dimension(500, 500));
        jLOGINADMIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jA_EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/EXIT_RED.png"))); // NOI18N
        jA_EXIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jA_EXITMouseClicked(evt);
            }
        });
        jLOGINADMIN.add(jA_EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 22, -1, -1));

        jA_ADMIN_ID.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jA_ADMIN_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jA_ADMIN_ID.setToolTipText("");
        jA_ADMIN_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 7, 0), 2));
        jLOGINADMIN.add(jA_ADMIN_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 177, 400, 45));

        jA_PASSWORD.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jA_PASSWORD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 7, 0), 2));
        jLOGINADMIN.add(jA_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 266, 400, 45));

        jA_KEYCARD.setFont(new java.awt.Font("Candara Light", 1, 12)); // NOI18N
        jA_KEYCARD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jA_KEYCARD.setToolTipText("");
        jA_KEYCARD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 7, 0), 2));
        jLOGINADMIN.add(jA_KEYCARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 349, 75, 30));

        jA_LOGIN.setBackground(new java.awt.Color(255, 165, 165));
        jA_LOGIN.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jA_LOGIN.setForeground(new java.awt.Color(102, 7, 0));
        jA_LOGIN.setText("LOG IN");
        jA_LOGIN.setBorder(null);
        jA_LOGIN.setBorderPainted(false);
        jA_LOGIN.setDefaultCapable(false);
        jA_LOGIN.setFocusPainted(false);
        jA_LOGIN.setFocusable(false);
        jA_LOGIN.setRequestFocusEnabled(false);
        jA_LOGIN.setRolloverEnabled(false);
        jA_LOGIN.setVerifyInputWhenFocusTarget(false);
        jA_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA_LOGINActionPerformed(evt);
            }
        });
        jLOGINADMIN.add(jA_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 415, 100, 40));

        jBG_ADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/LOGIN_ADMIN.png"))); // NOI18N
        jLOGINADMIN.add(jBG_ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jPanel1.add(jLOGINADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 88, 500, 500));

        OMP_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/ONEMOREPAGE (Logo).png"))); // NOI18N
        jPanel1.add(OMP_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 19, -1, -1));

        jAboutUs.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 12)); // NOI18N
        jAboutUs.setText("About Us");
        jPanel1.add(jAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 31, -1, -1));

        jbCreateAcc.setBackground(new java.awt.Color(0, 0, 0));
        jbCreateAcc.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 10)); // NOI18N
        jbCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        jbCreateAcc.setText("CREATE ACCOUNT");
        jbCreateAcc.setBorderPainted(false);
        jbCreateAcc.setDefaultCapable(false);
        jbCreateAcc.setFocusable(false);
        jbCreateAcc.setRequestFocusEnabled(false);
        jbCreateAcc.setRolloverEnabled(false);
        jbCreateAcc.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jbCreateAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 25, -1, 30));

        GUEST_PORTAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/STUDENT (main).png"))); // NOI18N
        GUEST_PORTAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUEST_PORTALMouseClicked(evt);
            }
        });
        jPanel1.add(GUEST_PORTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 238, -1, -1));

        LIBRARIAN_PORTAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/LIBRARIAN (main).png"))); // NOI18N
        LIBRARIAN_PORTAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LIBRARIAN_PORTALMouseClicked(evt);
            }
        });
        jPanel1.add(LIBRARIAN_PORTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 210, 200, -1));

        ADMIN_PORTAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/ADMIN (main).png"))); // NOI18N
        ADMIN_PORTAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADMIN_PORTALMouseClicked(evt);
            }
        });
        jPanel1.add(ADMIN_PORTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 130, -1, -1));

        jBestChoice.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jBestChoice.setForeground(new java.awt.Color(243, 206, 47));
        jBestChoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/Best Choice.png"))); // NOI18N
        jPanel1.add(jBestChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 160, -1, -1));

        ONEMOREPAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/ONE MORE PAGE.png"))); // NOI18N
        jPanel1.add(ONEMOREPAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jShortDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/Short Description.png"))); // NOI18N
        jPanel1.add(jShortDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 508, -1, -1));

        jDivider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_main/Main _ One More Page (DIVIDER).png"))); // NOI18N
        jPanel1.add(jDivider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean panelOpen = false;
    
    private void GUEST_PORTALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUEST_PORTALMouseClicked
        if (panelOpen) return;
       
        jLOGINGUEST.setVisible(true);
        LIBRARIAN_PORTAL.setEnabled(false);
        ADMIN_PORTAL.setEnabled(false);
        jAboutUs.setEnabled(false);
        jbCreateAcc.setEnabled(false);
        OMP_Logo.setEnabled(false);
        jBestChoice.setEnabled(false);
        ONEMOREPAGE.setEnabled(false);
        jShortDesc.setEnabled(false);
        jDivider.setEnabled(false);
        
        panelOpen = true;
    }//GEN-LAST:event_GUEST_PORTALMouseClicked

    private void jG_EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jG_EXITMouseClicked
        jLOGINGUEST.setVisible(false);
        LIBRARIAN_PORTAL.setEnabled(true);
        ADMIN_PORTAL.setEnabled(true);
        jAboutUs.setEnabled(true);
        jbCreateAcc.setEnabled(true);
        OMP_Logo.setEnabled(true);
        jBestChoice.setEnabled(true);
        ONEMOREPAGE.setEnabled(true);
        jShortDesc.setEnabled(true);
        jDivider.setEnabled(true);
        
        panelOpen = false;
    }//GEN-LAST:event_jG_EXITMouseClicked

    private void jL_EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_EXITMouseClicked
        jLOGINLIBRARIAN.setVisible(false);
        GUEST_PORTAL.setEnabled(true);
        ADMIN_PORTAL.setEnabled(true);
        jAboutUs.setEnabled(true);
        jbCreateAcc.setEnabled(true);
        OMP_Logo.setEnabled(true);
        jBestChoice.setEnabled(true);
        ONEMOREPAGE.setEnabled(true);
        jShortDesc.setEnabled(true);
        jDivider.setEnabled(true);
        
        panelOpen = false;
    }//GEN-LAST:event_jL_EXITMouseClicked

    private void LIBRARIAN_PORTALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIBRARIAN_PORTALMouseClicked
        if (panelOpen) return;
        
        jLOGINLIBRARIAN.setVisible(true);
        GUEST_PORTAL.setEnabled(false);
        ADMIN_PORTAL.setEnabled(false);
        jAboutUs.setEnabled(false);
        jbCreateAcc.setEnabled(false);
        OMP_Logo.setEnabled(false);
        jBestChoice.setEnabled(false);
        ONEMOREPAGE.setEnabled(false);
        jShortDesc.setEnabled(false);
        jDivider.setEnabled(false);
        
        panelOpen = true;
    }//GEN-LAST:event_LIBRARIAN_PORTALMouseClicked
    
    
    private void jA_EXITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jA_EXITMouseClicked
        jLOGINADMIN.setVisible(false);
        LIBRARIAN_PORTAL.setEnabled(true);
        GUEST_PORTAL.setEnabled(true);
        jAboutUs.setEnabled(true);
        jbCreateAcc.setEnabled(true);
        OMP_Logo.setEnabled(true);
        jBestChoice.setEnabled(true);
        ONEMOREPAGE.setEnabled(true);
        jShortDesc.setEnabled(true);
        jDivider.setEnabled(true);
        
        panelOpen = false;
    }//GEN-LAST:event_jA_EXITMouseClicked

    private void ADMIN_PORTALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADMIN_PORTALMouseClicked
        if (panelOpen) return;
        
        jLOGINADMIN.setVisible(true);
        LIBRARIAN_PORTAL.setEnabled(false);
        GUEST_PORTAL.setEnabled(false);
        jAboutUs.setEnabled(false);
        jbCreateAcc.setEnabled(false);
        OMP_Logo.setEnabled(false);
        jBestChoice.setEnabled(false);
        ONEMOREPAGE.setEnabled(false);
        jShortDesc.setEnabled(false);
        jDivider.setEnabled(false);
        
        panelOpen = true;
    }//GEN-LAST:event_ADMIN_PORTALMouseClicked

    private void jA_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA_LOGINActionPerformed
        String adminID = jA_ADMIN_ID.getText();
        String adminpassword = new String(jA_PASSWORD.getPassword());
        String keycard = jA_KEYCARD.getText();

      if (adminID.isEmpty() || adminpassword.isEmpty() || keycard.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            LoginDatabase.getInstance().loginAdmin(adminID, adminpassword, keycard, this);
        }

    }//GEN-LAST:event_jA_LOGINActionPerformed

    private void jL_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jL_LOGINActionPerformed
        String librarianID = jL_LIBRARIAN_ID.getText();
        String librarianpassword = new String(jL_PASSWORD.getPassword());

        if(librarianID.equals("L-616") && librarianpassword.equals("librarian")) {
            JOptionPane.showMessageDialog(this, "Login successful!");
            LIBRARIAN dashbaord = new LIBRARIAN();
            dashbaord.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Librarian ID and Password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jL_LOGINActionPerformed

    private void jG_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jG_LOGINActionPerformed
        String guestusername = jG_USERNAME.getText();
        String guestpassword = new String(jG_PASSWORD.getPassword());

        if(guestusername.isEmpty() || guestpassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        } else {
            LoginDatabase.getInstance().loginStudent(guestusername, guestpassword, this);
        }
    }//GEN-LAST:event_jG_LOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADMIN_PORTAL;
    private javax.swing.JLabel GUEST_PORTAL;
    private javax.swing.JLabel LIBRARIAN_PORTAL;
    private javax.swing.JLabel OMP_Logo;
    private javax.swing.JLabel ONEMOREPAGE;
    private javax.swing.JTextField jA_ADMIN_ID;
    private javax.swing.JLabel jA_EXIT;
    private javax.swing.JTextField jA_KEYCARD;
    private javax.swing.JButton jA_LOGIN;
    private javax.swing.JPasswordField jA_PASSWORD;
    private javax.swing.JLabel jAboutUs;
    private javax.swing.JLabel jBG_ADMIN;
    private javax.swing.JLabel jBG_GUEST;
    private javax.swing.JLabel jBG_LIBRARIAN;
    private javax.swing.JLabel jBestChoice;
    private javax.swing.JLabel jDivider;
    private javax.swing.JLabel jG_EXIT;
    private javax.swing.JButton jG_LOGIN;
    private javax.swing.JPasswordField jG_PASSWORD;
    private javax.swing.JTextField jG_USERNAME;
    private javax.swing.JPanel jLOGINADMIN;
    private javax.swing.JPanel jLOGINGUEST;
    private javax.swing.JPanel jLOGINLIBRARIAN;
    private javax.swing.JLabel jL_EXIT;
    private javax.swing.JTextField jL_LIBRARIAN_ID;
    private javax.swing.JButton jL_LOGIN;
    private javax.swing.JPasswordField jL_PASSWORD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jShortDesc;
    private javax.swing.JButton jbCreateAcc;
    // End of variables declaration//GEN-END:variables
}
